---
title: "KLM Plots"
author: "Abby Steckel"
date: "10/18/2021"
output:
  word_document: default
  html_document: default
---

```{r}
## data manipulation
library(plyr)
library(reshape2)

## output
library(ggplot2)
library(xtable)

#packages for loading in compressed data 
library(R.utils)
library(tidyverse)
combine <- read.csv('/Users/abbysteckel/Desktop/combined.csv.gz')
combine <- na_if(combine, "")

#subset to just Black or white folks 
df <- combine[combine$RACE %in% c("black", "white"), ]
df$RACE <- ifelse(df$RACE == "black", 1, 0)

#create sentence levels  
sentence.levels <- c(
  'at least 0.03',
  'at least 1',
  'at least 6',
  'at least 12',
  'at least 24', 
  'at least 48', 
  'at least 72', 
  'at least 96', 
  'at least 120', 
  'at least 180', 
  'at least 240', 
  'at least 300', 
  'at least 360', 
  'at least 420', 
  'at least 480', 
  'at least 540', 
  'at least 600', 
  'at least 720', 
  'at least 840', 
  'at least 960', 
  'at least 1080'
)

#add a categorical sentence levels variable to the df dataframe 
df <- df %>% mutate ( # https://dplyr.tidyverse.org/reference/mutate.html
    sentence.levels = case_when( # https://dplyr.tidyverse.org/reference/case_when.html 
      SENTENCE >= 1080 ~ 'at least 1080',
      SENTENCE >= 960 ~ 'at least 960',
      SENTENCE >= 840 ~ 'at least 840', 
      SENTENCE >= 720 ~ 'at least 720', 
      SENTENCE >= 600 ~ 'at least 600', 
      SENTENCE >= 540 ~ 'at least 540', 
      SENTENCE >= 480 ~ 'at least 480', 
      SENTENCE >= 420 ~ 'at least 420', 
      SENTENCE >= 360 ~ 'at least 360', 
      SENTENCE >= 300 ~ 'at least 300', 
      SENTENCE >= 240 ~ 'at least 240', 
      SENTENCE >= 180 ~ 'at least 180', 
      SENTENCE >= 120 ~ 'at least 120', 
      SENTENCE >= 96 ~ 'at least 96', 
      SENTENCE >= 72 ~ 'at least 72', 
      SENTENCE >= 48 ~ 'at least 48', 
      SENTENCE >= 24 ~ 'at least 24', 
      SENTENCE >= 12 ~ 'at least 12', 
      SENTENCE >= 6 ~ 'at least 6', 
      SENTENCE >= 1 ~ 'at least 1', 
      SENTENCE >= 0.03 ~ 'at least 0.03'
    ))

thresholds <- c(0.03, 1, 6, 12, 24, 48, 72, 96, 120, 240, 300, 360, 420, 480, 540, 600, 720, 840, 960, 1080)

## set white as base level
races.abbr <- c('white', 'black')
races <- c('white', 'black')
df$race <- factor(df$RACE, labels = races)

##########
## prep ##
##########

red <- '#A31F34'
blue <- '#325585'

odds.to.mean <- function(x){ x / (x + 1) }
mean.to.odds <- function(x){ x / (1 - x) }

##################
## load results ##
##################

## bounds results
ndraws <- 5000
alpha <- .95 #desired significance level 
results.fname <- sprintf('bounds_results_n%s_alpha%s_blackwhite_sentencing.rds',
                         ndraws,
                         alpha * 100
                         )
setwd("/Users/abbysteckel/Desktop/S&DS_491/Sentencing_Data/")
results <- readRDS(results.fname) 
#add column containing the number of black people in the dataset (n = 150372)
results$n.minority <- sum(df$race == 'black', na.rm = TRUE) 
```


*This section is copied without modification from KLM. Ultimately, I plan to research reasonable values of rho based on existing scholarship on convictions and sentencing.*
```{r}
####################################################################
## plausible values for proportion of racial stops                ##
## based on gelman fagan kiss (2007), analysis of nypd s&f policy ##
## and goel rao shroff(2016), precinct or prejudice               ##
####################################################################

## gfk table 1: racial differences in stop rates that cannot explained by
##   - crime type (violent / weapons / property / drug)
##   - racial group's criminality (as previous year's dcjs arrest rates)
##   - precincts
gfk17 <- read.csv('/Users/abbysteckel/Desktop/S&DS_491/KLM Replication Materials/GelmanFaganKissTable1.csv')
gfk17 <- dcast(melt(gfk17, variable.name = 'crime.type'), ... ~ parameter)

## gfk p820: convert to stops per prev year's arrest, by precinct & crime type
##   "rates of stops (compared with previous year’s arrests)
##    for each ethnic group, e^(µ+α_e)"
gfk17$whites.stops.per.arrest <- exp(gfk17$intercept + gfk17$whites)
gfk17$blacks.stops.per.arrest <- exp(gfk17$intercept + gfk17$blacks)

## gfk proportion of excess stops, by precinct & crime type
gfk17$blacks.stops.excess <-
  (gfk17$blacks.stops.per.arrest - gfk17$whites.stops.per.arrest) /
  gfk17$blacks.stops.per.arrest

## or simply do this:
all.equal(gfk17$blacks.stops.excess,
          1 - exp(gfk17$whites - gfk17$blacks),
          tolerance = 1e-6
          )

## gfk p817: "each of the three [black population proportion] categories
##            represents roughly 1/3 of the precincts"
prop.weights <- c(
  '<10%' = 1/3,
  '10-40%' = 1/3,
  '>40%' = 1/3
)
gfk17$prop.weight <- prop.weights[gfk17$prop.black]

## gfk figure 2: suspected crime type as percentage of all stops
crime.type.weights <- c(
  violent = .25,
  weapons = .44,
  property = .2,
  drug = .11
)
gfk17$crime.type.weight <- crime.type.weights[gfk17$crime.type]

## gfk racial stop proportions, based on
##   (a) minority stops per each previous year's minority arrest
##   (b) white stops per each previous year's white arrest
##   racially motivated stops are a-b, proportion of minority stops is (a-b)/a
##   we take weighted average of (a-b)/a by precinct type & crime type
black.rs.gfk <- weighted.mean(
  x = gfk17$blacks.stops.excess,
  w = gfk17$prop.weight * gfk17$crime.type.weight
)

## grs racial stop proportions
black.rs.grs <- (3.8 - 2.5) / 3.8

## vertical lines based on prior work
annotations <- data.frame(treat.race = 'black',
                          rho = black.rs.gfk,
                          text = 'GFK (2007)')
```


```{r}
#################
## prep labels ##
#################

## labels for plots
results$thresh.label <- factor(
  sentence.levels[results$thresh],
  levels = sentence.levels,
  labels = gsub('\n', ' ', sentence.levels),
  ordered = TRUE
) #there are 200 of each threshold label: 100 rho values x 2 treatment effect estimators 

results$race.label <- factor(
  results$treat.race, #treat.race = black 
  levels = c('black'),
  labels = c('Black civilians'),
  ordered = TRUE
)

results$mod.label <- factor(
  results$mod.type,
  levels = c('base', 'full'),
  labels = c('Baseline specification', 'Full specification'),
  ordered = TRUE
)

annotations$race.label <- factor(
  annotations$treat.race,
  levels = c('black'),
  labels = c('Black civilians'),
  ordered = TRUE
)
```


```{r}
##################################
## interpretation for main text ##
##################################

results$rho <- round(results$rho, 2)  # fix minor floating point issue

## naive atest, baseline specification
naive.black.base <- results[
  results$mod.type == 'base' &
    results$treat.race == 'black' &
    results$rho == 0 &
    results$qoi == 'atest',
  ]
## bias-corrected atest, baseline specification
biascorrect.black.base <- results[
  results$mod.type == 'base' &
    results$treat.race == 'black' &
    results$rho == round(black.rs.gfk, 2) &
    results$qoi == 'atest',
  ]

##naive estimate for black (vs white) x number of black encounters
naive.black.base$excess <-
  naive.black.base$est * naive.black.base$n.minority
naive.excess <- ## naive.hispanic.base$excess +
  naive.black.base$excess
names(naive.excess) <- naive.black.base$thresh.label

## bias-corrected atest for black (vs white) x number of black encounters
biascorrect.black.base$excess <-
  biascorrect.black.base$est * biascorrect.black.base$n.minority
biascorrect.excess <-
  ## biascorrect.hispanic.base$excess +
  biascorrect.black.base$excess
## results
excess.base <-
  cbind('naive' = naive.excess, 'bias-corrected' = biascorrect.excess)
excess.base

#PROBLEM: the bias-corrected ATEs are way too big  
```


```{r}
#################
## plot bounds ##
#################
#PROBLEM: bounds for thresh = 1 aren't showing up on the graph because the upper and lower bounds are exactly equal 
sort(table(df$sentence.levels)) #most frequent sentence is at least 24, i = 5. next is at least 12, i = 4. 
#when I set thresh = 5,the max y val is around 300. for i = 4, it's 250. least frequent sentence is at least 720, i = 18. WHY DO MAX Ys DIFFER SO MUCH? 
thresh <- 1

#QUESTION: What's the expected relationship between ATE_M=1 and ATT_M=1?  

#checking values of min.cilo and max.cihi
min(results[results$thresh >= thresh & results$qoi == 'ates',"min.cilo"], na.rm = TRUE)
max(results[results$thresh >= thresh & results$qoi == 'ates',"min.cilo"], na.rm=TRUE)

#should this be results$thresh >= thresh so as to include all observations with convictions above the threshold? 
ggplot(results[results$thresh == thresh &
                 results$qoi == 'ates',
               ],
       aes(x = rho) #x-axis is value of rho 
       ) +
  geom_hline(yintercept = 0, #draw x-axis
             ) + 
  geom_ribbon(aes(ymin = min.cilo * nrow(df) / 1000, 
                  ymax = max.cihi * nrow(df) / 1000
                  ),
              fill = paste0(red, '80')
              ) +
  geom_ribbon(aes(ymin = min * nrow(df) / 1000,
                  ymax = max * nrow(df) / 1000,
                  fill = 'TE_S'
                  )
              ) +
  geom_line(aes(y = est * n.minority / 1000,
                linetype = 'TE_ST',
                ),
            results[results$thresh == thresh &
                      results$qoi == 'atest',
                    ],
            color = 'black',
            size = 1
            ) +
  geom_point(aes(y = est * nrow(df) / 1000,
                 color = 'naive'
                 ),
             data = results[results$thresh == thresh & results$rho == 0,],
             color = blue,
             size = 2
             ) +
  geom_errorbar(aes(ymin = est.cilo * nrow(df) / 1000,
                    ymax = est.cihi * nrow(df) / 1000,
                    color = 'naive'
                    ),
                data = results[results$thresh == thresh & results$rho == 0,],
                width = 1,
                size = 1
                ) +
  geom_vline(aes(xintercept = rho),
             data = annotations[annotations$treat.race == 'black',],
             linetype = 'dashed',
             size = .25
             ) +
  geom_text(aes(label = text),
            data = annotations[annotations$treat.race == 'black',],
            y = 1100,
            size = 3,
            hjust = 1,
            vjust = -.5,
            angle = 90
            ) +
  theme(legend.position = 'bottom',
        legend.key.size = unit(1, 'cm'),
        legend.spacing.x = unit(.05, 'cm'),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(linetype = 'dashed')
        ) +
  guides(color = guide_legend(title = NULL, order = 1),
         linetype = guide_legend(title = NULL, order = 2),
         fill = guide_legend(title = NULL, order = 3)
         ) +
  scale_color_manual(
    name = 'x',
    values = c('naive' = blue,
               'TE_S' = NA,
               'TE_ST' = NA
               ),
    labels = c('naive' = expression('naïve ATE'['M=1'] %*% ' #{stopped}'),
               'TE_S' = expression('ATE'['M=1'] %*% ' #{stopped}'),
               'TE_ST' = expression('ATT'['M=1'] %*% ' #{stopped minorities}')
               )
  ) +
  scale_fill_manual(name = 'x',
                        values = c('naive' = NA,
                                   'TE_S' = red,
                                   'TE_ST' = NA
                                   ),
    labels = c('naive' = expression('naïve ATE'['M=1'] %*% ' #{convicted}'),
               'TE_S' = expression('ATE'['M=1'] %*% ' #{convicted}'),
               'TE_ST' = expression('ATT'['M=1'] %*% ' #{convicted minorities}')
               )
    ) +
  scale_linetype_manual(
    name = 'x',
    values = c('naive' = NA,
               'TE_S' = NA,
               'TE_ST' = 'dashed'
               ),
    labels = c('naive' = expression('naïve ATE'['M=1'] %*% ' #{convicted}'),
               'TE_S' = expression('ATE'['M=1'] %*% ' #{convicted}'),
               'TE_ST' = expression('ATT'['M=1'] %*% ' #{convicted minorities}')
               )
  ) +
  ylab('Civilians subject to racially\ndiscriminatory sentence length\n(thousands)\n') +
  xlab('\nProportion of racially discriminatory stops') +
  xlim(0, 1) +
  facet_grid(. ~ race.label) +
  theme(legend.text = element_text(size = 10), axis.title.y = element_text(size=10), axis.title.x = element_text(size=10))
#ggsave('pics/bounds_hands_correct_blackwhite.pdf', width = 13, height = 6)

#results[1:100, ] #Problem: compared to KLM, there's a more dramatic difference between CI when rho = 0 and when rho = 0.99.
#sum(table(df$sentence.levels))
```

```{r}
thresh <- 5

ggplot(results[results$thresh == thresh &
                 results$qoi == 'ates',
               ],
       aes(x = rho) #x-axis is value of rho 
       ) +
  geom_hline(yintercept = 0, #draw x-axis
             ) + 
  geom_ribbon(aes(ymin = min.cilo * nrow(df) / 1000, 
                  ymax = max.cihi * nrow(df) / 1000
                  ),
              fill = paste0(red, '80')
              ) +
  geom_ribbon(aes(ymin = min * nrow(df) / 1000,
                  ymax = max * nrow(df) / 1000,
                  fill = 'TE_S'
                  )
              ) +
  geom_line(aes(y = est * n.minority / 1000,
                linetype = 'TE_ST',
                ),
            results[results$thresh == thresh &
                      results$qoi == 'atest',
                    ],
            color = 'black',
            size = 1
            ) +
  geom_point(aes(y = est * nrow(df) / 1000,
                 color = 'naive'
                 ),
             data = results[results$thresh == thresh & results$rho == 0,],
             color = blue,
             size = 2
             ) +
  geom_errorbar(aes(ymin = est.cilo * nrow(df) / 1000,
                    ymax = est.cihi * nrow(df) / 1000,
                    color = 'naive'
                    ),
                data = results[results$thresh == thresh & results$rho == 0,],
                width = 1,
                size = 1
                ) +
  geom_vline(aes(xintercept = rho),
             data = annotations[annotations$treat.race == 'black',],
             linetype = 'dashed',
             size = .25
             ) +
  geom_text(aes(label = text),
            data = annotations[annotations$treat.race == 'black',],
            y = 1100,
            size = 3,
            hjust = 1,
            vjust = -.5,
            angle = 90
            ) +
  theme(legend.position = 'bottom',
        legend.key.size = unit(1, 'cm'),
        legend.spacing.x = unit(.05, 'cm'),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(linetype = 'dashed')
        ) +
  guides(color = guide_legend(title = NULL, order = 1),
         linetype = guide_legend(title = NULL, order = 2),
         fill = guide_legend(title = NULL, order = 3)
         ) +
  scale_color_manual(
    name = 'x',
    values = c('naive' = blue,
               'TE_S' = NA,
               'TE_ST' = NA
               ),
    labels = c('naive' = expression('naïve ATE'['M=1'] %*% ' #{stopped}'),
               'TE_S' = expression('ATE'['M=1'] %*% ' #{stopped}'),
               'TE_ST' = expression('ATT'['M=1'] %*% ' #{stopped minorities}')
               )
  ) +
  scale_fill_manual(name = 'x',
                        values = c('naive' = NA,
                                   'TE_S' = red,
                                   'TE_ST' = NA
                                   ),
    labels = c('naive' = expression('naïve ATE'['M=1'] %*% ' #{convicted}'),
               'TE_S' = expression('ATE'['M=1'] %*% ' #{convicted}'),
               'TE_ST' = expression('ATT'['M=1'] %*% ' #{convicted minorities}')
               )
    ) +
  scale_linetype_manual(
    name = 'x',
    values = c('naive' = NA,
               'TE_S' = NA,
               'TE_ST' = 'dashed'
               ),
    labels = c('naive' = expression('naïve ATE'['M=1'] %*% ' #{convicted}'),
               'TE_S' = expression('ATE'['M=1'] %*% ' #{convicted}'),
               'TE_ST' = expression('ATT'['M=1'] %*% ' #{convicted minorities}')
               )
  ) +
  ylab('Civilians subject to racially\ndiscriminatory sentence length\n(thousands)\n') +
  xlab('\nProportion of racially discriminatory stops') +
  xlim(0, 1) +
  facet_grid(. ~ race.label) +
  theme(legend.text = element_text(size = 10), axis.title.y = element_text(size=10), axis.title.x = element_text(size=10))
```

```{r}
thresh <- 20

ggplot(results[results$thresh == thresh &
                 results$qoi == 'ates',
               ],
       aes(x = rho) #x-axis is value of rho 
       ) +
  geom_hline(yintercept = 0, #draw x-axis
             ) + 
  geom_ribbon(aes(ymin = min.cilo * nrow(df) / 1000, 
                  ymax = max.cihi * nrow(df) / 1000
                  ),
              fill = paste0(red, '80')
              ) +
  geom_ribbon(aes(ymin = min * nrow(df) / 1000,
                  ymax = max * nrow(df) / 1000,
                  fill = 'TE_S'
                  )
              ) +
  geom_line(aes(y = est * n.minority / 1000,
                linetype = 'TE_ST',
                ),
            results[results$thresh == thresh &
                      results$qoi == 'atest',
                    ],
            color = 'black',
            size = 1
            ) +
  geom_point(aes(y = est * nrow(df) / 1000,
                 color = 'naive'
                 ),
             data = results[results$thresh == thresh & results$rho == 0,],
             color = blue,
             size = 2
             ) +
  geom_errorbar(aes(ymin = est.cilo * nrow(df) / 1000,
                    ymax = est.cihi * nrow(df) / 1000,
                    color = 'naive'
                    ),
                data = results[results$thresh == thresh & results$rho == 0,],
                width = 1,
                size = 1
                ) +
  geom_vline(aes(xintercept = rho),
             data = annotations[annotations$treat.race == 'black',],
             linetype = 'dashed',
             size = .25
             ) +
  geom_text(aes(label = text),
            data = annotations[annotations$treat.race == 'black',],
            y = 1100,
            size = 3,
            hjust = 1,
            vjust = -.5,
            angle = 90
            ) +
  theme(legend.position = 'bottom',
        legend.key.size = unit(1, 'cm'),
        legend.spacing.x = unit(.05, 'cm'),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(linetype = 'dashed')
        ) +
  guides(color = guide_legend(title = NULL, order = 1),
         linetype = guide_legend(title = NULL, order = 2),
         fill = guide_legend(title = NULL, order = 3)
         ) +
  scale_color_manual(
    name = 'x',
    values = c('naive' = blue,
               'TE_S' = NA,
               'TE_ST' = NA
               ),
    labels = c('naive' = expression('naïve ATE'['M=1'] %*% ' #{stopped}'),
               'TE_S' = expression('ATE'['M=1'] %*% ' #{stopped}'),
               'TE_ST' = expression('ATT'['M=1'] %*% ' #{stopped minorities}')
               )
  ) +
  scale_fill_manual(name = 'x',
                        values = c('naive' = NA,
                                   'TE_S' = red,
                                   'TE_ST' = NA
                                   ),
    labels = c('naive' = expression('naïve ATE'['M=1'] %*% ' #{convicted}'),
               'TE_S' = expression('ATE'['M=1'] %*% ' #{convicted}'),
               'TE_ST' = expression('ATT'['M=1'] %*% ' #{convicted minorities}')
               )
    ) +
  scale_linetype_manual(
    name = 'x',
    values = c('naive' = NA,
               'TE_S' = NA,
               'TE_ST' = 'dashed'
               ),
    labels = c('naive' = expression('naïve ATE'['M=1'] %*% ' #{convicted}'),
               'TE_S' = expression('ATE'['M=1'] %*% ' #{convicted}'),
               'TE_ST' = expression('ATT'['M=1'] %*% ' #{convicted minorities}')
               )
  ) +
  ylab('Civilians subject to racially\ndiscriminatory sentence length\n(thousands)\n') +
  xlab('\nProportion of racially discriminatory stops') +
  xlim(0, 1) +
  facet_grid(. ~ race.label) +
  theme(legend.text = element_text(size = 10), axis.title.y = element_text(size=10), axis.title.x = element_text(size=10))
```


